// AUTO-GENERATED by pregen_numeric.js — do not edit by hand
// Replaces all new Function() calls in numeric.js for MV3 CSP compliance
(function () {
  numeric['addVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] + y[i]; } return ret; };
  numeric['addSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x + y[i]; } return ret; };
  numeric['addVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] + y; } return ret; };
  numeric['add'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['addVV'], VS = numeric['addVS'], SV = numeric['addSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x += y;
    }
    return x;
  };
  numeric['addeqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] += x[i]; } };
  numeric['addeqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] += x; } };
  numeric['addeq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['addeqV'], S = numeric['addeqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['subVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] - y[i]; } return ret; };
  numeric['subSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x - y[i]; } return ret; };
  numeric['subVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] - y; } return ret; };
  numeric['sub'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['subVV'], VS = numeric['subVS'], SV = numeric['subSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x -= y;
    }
    return x;
  };
  numeric['subeqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] -= x[i]; } };
  numeric['subeqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] -= x; } };
  numeric['subeq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['subeqV'], S = numeric['subeqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['mulVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] * y[i]; } return ret; };
  numeric['mulSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x * y[i]; } return ret; };
  numeric['mulVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] * y; } return ret; };
  numeric['mul'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['mulVV'], VS = numeric['mulVS'], SV = numeric['mulSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x *= y;
    }
    return x;
  };
  numeric['muleqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] *= x[i]; } };
  numeric['muleqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] *= x; } };
  numeric['muleq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['muleqV'], S = numeric['muleqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['divVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] / y[i]; } return ret; };
  numeric['divSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x / y[i]; } return ret; };
  numeric['divVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] / y; } return ret; };
  numeric['div'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['divVV'], VS = numeric['divVS'], SV = numeric['divSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x /= y;
    }
    return x;
  };
  numeric['diveqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] /= x[i]; } };
  numeric['diveqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] /= x; } };
  numeric['diveq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['diveqV'], S = numeric['diveqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['modVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] % y[i]; } return ret; };
  numeric['modSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x % y[i]; } return ret; };
  numeric['modVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] % y; } return ret; };
  numeric['mod'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['modVV'], VS = numeric['modVS'], SV = numeric['modSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x %= y;
    }
    return x;
  };
  numeric['modeqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] %= x[i]; } };
  numeric['modeqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] %= x; } };
  numeric['modeq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['modeqV'], S = numeric['modeqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['andVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] && y[i]; } return ret; };
  numeric['andSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x && y[i]; } return ret; };
  numeric['andVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] && y; } return ret; };
  numeric['and'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['andVV'], VS = numeric['andVS'], SV = numeric['andSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = x && y;
    }
    return x;
  };
  numeric['andeqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] && x[i]; } };
  numeric['andeqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] && x; } };
  numeric['andeq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['andeqV'], S = numeric['andeqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['orVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] || y[i]; } return ret; };
  numeric['orSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x || y[i]; } return ret; };
  numeric['orVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] || y; } return ret; };
  numeric['or'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['orVV'], VS = numeric['orVS'], SV = numeric['orSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = x || y;
    }
    return x;
  };
  numeric['oreqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] || x[i]; } };
  numeric['oreqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] || x; } };
  numeric['oreq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['oreqV'], S = numeric['oreqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['eqVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] === y[i]; } return ret; };
  numeric['eqSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x === y[i]; } return ret; };
  numeric['eqVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] === y; } return ret; };
  numeric['eq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['eqVV'], VS = numeric['eqVS'], SV = numeric['eqSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = x === y;
    }
    return x;
  };
  numeric['eqeqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] === x[i]; } };
  numeric['eqeqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] === x; } };
  numeric['eqeq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['eqeqV'], S = numeric['eqeqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['neqVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] !== y[i]; } return ret; };
  numeric['neqSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x !== y[i]; } return ret; };
  numeric['neqVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] !== y; } return ret; };
  numeric['neq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['neqVV'], VS = numeric['neqVS'], SV = numeric['neqSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = x !== y;
    }
    return x;
  };
  numeric['neqeqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] !== x[i]; } };
  numeric['neqeqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] !== x; } };
  numeric['neqeq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['neqeqV'], S = numeric['neqeqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['ltVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] < y[i]; } return ret; };
  numeric['ltSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x < y[i]; } return ret; };
  numeric['ltVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] < y; } return ret; };
  numeric['lt'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['ltVV'], VS = numeric['ltVS'], SV = numeric['ltSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = x < y;
    }
    return x;
  };
  numeric['lteqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] < x[i]; } };
  numeric['lteqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] < x; } };
  numeric['lteq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['lteqV'], S = numeric['lteqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['gtVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] > y[i]; } return ret; };
  numeric['gtSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x > y[i]; } return ret; };
  numeric['gtVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] > y; } return ret; };
  numeric['gt'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['gtVV'], VS = numeric['gtVS'], SV = numeric['gtSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = x > y;
    }
    return x;
  };
  numeric['gteqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] > x[i]; } };
  numeric['gteqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] > x; } };
  numeric['gteq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['gteqV'], S = numeric['gteqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['leqVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] <= y[i]; } return ret; };
  numeric['leqSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x <= y[i]; } return ret; };
  numeric['leqVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] <= y; } return ret; };
  numeric['leq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['leqVV'], VS = numeric['leqVS'], SV = numeric['leqSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = x <= y;
    }
    return x;
  };
  numeric['leqeqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] <= x[i]; } };
  numeric['leqeqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] <= x; } };
  numeric['leqeq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['leqeqV'], S = numeric['leqeqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['geqVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] >= y[i]; } return ret; };
  numeric['geqSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x >= y[i]; } return ret; };
  numeric['geqVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] >= y; } return ret; };
  numeric['geq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['geqVV'], VS = numeric['geqVS'], SV = numeric['geqSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = x >= y;
    }
    return x;
  };
  numeric['geqeqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] >= x[i]; } };
  numeric['geqeqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i] >= x; } };
  numeric['geqeq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['geqeqV'], S = numeric['geqeqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['bandVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] & y[i]; } return ret; };
  numeric['bandSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x & y[i]; } return ret; };
  numeric['bandVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] & y; } return ret; };
  numeric['band'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['bandVV'], VS = numeric['bandVS'], SV = numeric['bandSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x &= y;
    }
    return x;
  };
  numeric['bandeqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] &= x[i]; } };
  numeric['bandeqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] &= x; } };
  numeric['bandeq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['bandeqV'], S = numeric['bandeqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['borVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] | y[i]; } return ret; };
  numeric['borSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x | y[i]; } return ret; };
  numeric['borVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] | y; } return ret; };
  numeric['bor'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['borVV'], VS = numeric['borVS'], SV = numeric['borSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x |= y;
    }
    return x;
  };
  numeric['boreqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] |= x[i]; } };
  numeric['boreqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] |= x; } };
  numeric['boreq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['boreqV'], S = numeric['boreqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['bxorVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] ^ y[i]; } return ret; };
  numeric['bxorSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x ^ y[i]; } return ret; };
  numeric['bxorVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] ^ y; } return ret; };
  numeric['bxor'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['bxorVV'], VS = numeric['bxorVS'], SV = numeric['bxorSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x ^= y;
    }
    return x;
  };
  numeric['bxoreqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] ^= x[i]; } };
  numeric['bxoreqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] ^= x; } };
  numeric['bxoreq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['bxoreqV'], S = numeric['bxoreqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['lshiftVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] << y[i]; } return ret; };
  numeric['lshiftSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x << y[i]; } return ret; };
  numeric['lshiftVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] << y; } return ret; };
  numeric['lshift'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['lshiftVV'], VS = numeric['lshiftVS'], SV = numeric['lshiftSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x <<= y;
    }
    return x;
  };
  numeric['lshifteqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] <<= x[i]; } };
  numeric['lshifteqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] <<= x; } };
  numeric['lshifteq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['lshifteqV'], S = numeric['lshifteqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['rshiftVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] >> y[i]; } return ret; };
  numeric['rshiftSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x >> y[i]; } return ret; };
  numeric['rshiftVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] >> y; } return ret; };
  numeric['rshift'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['rshiftVV'], VS = numeric['rshiftVS'], SV = numeric['rshiftSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x >>= y;
    }
    return x;
  };
  numeric['rshifteqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] >>= x[i]; } };
  numeric['rshifteqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] >>= x; } };
  numeric['rshifteq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['rshifteqV'], S = numeric['rshifteqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['rrshiftVV'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] >>> y[i]; } return ret; };
  numeric['rrshiftSV'] = function (x, y) { var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x >>> y[i]; } return ret; };
  numeric['rrshiftVS'] = function (x, y) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i] >>> y; } return ret; };
  numeric['rrshift'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['rrshiftVV'], VS = numeric['rrshiftVS'], SV = numeric['rrshiftSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x >>>= y;
    }
    return x;
  };
  numeric['rrshifteqV'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] >>>= x[i]; } };
  numeric['rrshifteqS'] = function (ret, x) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] >>>= x; } };
  numeric['rrshifteq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['rrshifteqV'], S = numeric['rrshifteqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['atan2VV'] = function (x, y) { var atan2 = Math.atan2; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = atan2(x[i], y[i]); } return ret; };
  numeric['atan2SV'] = function (x, y) { var atan2 = Math.atan2; var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = atan2(x, y[i]); } return ret; };
  numeric['atan2VS'] = function (x, y) { var atan2 = Math.atan2; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = atan2(x[i], y); } return ret; };
  numeric['atan2'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['atan2VV'], VS = numeric['atan2VS'], SV = numeric['atan2SV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = Math.atan2(x, y);
    }
    return x;
  };
  numeric['atan2'] = numeric['atan2'];
  numeric['atan2eqV'] = function (ret, x) { var atan2 = Math.atan2; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = atan2(ret[i], x[i]); } };
  numeric['atan2eqS'] = function (ret, x) { var atan2 = Math.atan2; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = atan2(ret[i], x); } };
  numeric['atan2eq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['atan2eqV'], S = numeric['atan2eqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['powVV'] = function (x, y) { var pow = Math.pow; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = pow(x[i], y[i]); } return ret; };
  numeric['powSV'] = function (x, y) { var pow = Math.pow; var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = pow(x, y[i]); } return ret; };
  numeric['powVS'] = function (x, y) { var pow = Math.pow; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = pow(x[i], y); } return ret; };
  numeric['pow'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['powVV'], VS = numeric['powVS'], SV = numeric['powSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = Math.pow(x, y);
    }
    return x;
  };
  numeric['pow'] = numeric['pow'];
  numeric['poweqV'] = function (ret, x) { var pow = Math.pow; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = pow(ret[i], x[i]); } };
  numeric['poweqS'] = function (ret, x) { var pow = Math.pow; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = pow(ret[i], x); } };
  numeric['poweq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['poweqV'], S = numeric['poweqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['maxVV'] = function (x, y) { var max = Math.max; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = max(x[i], y[i]); } return ret; };
  numeric['maxSV'] = function (x, y) { var max = Math.max; var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = max(x, y[i]); } return ret; };
  numeric['maxVS'] = function (x, y) { var max = Math.max; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = max(x[i], y); } return ret; };
  numeric['max'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['maxVV'], VS = numeric['maxVS'], SV = numeric['maxSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = Math.max(x, y);
    }
    return x;
  };
  numeric['max'] = numeric['max'];
  numeric['maxeqV'] = function (ret, x) { var max = Math.max; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = max(ret[i], x[i]); } };
  numeric['maxeqS'] = function (ret, x) { var max = Math.max; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = max(ret[i], x); } };
  numeric['maxeq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['maxeqV'], S = numeric['maxeqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['minVV'] = function (x, y) { var min = Math.min; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = min(x[i], y[i]); } return ret; };
  numeric['minSV'] = function (x, y) { var min = Math.min; var _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = min(x, y[i]); } return ret; };
  numeric['minVS'] = function (x, y) { var min = Math.min; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = min(x[i], y); } return ret; };
  numeric['min'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var VV = numeric['minVV'], VS = numeric['minVS'], SV = numeric['minSV'];
    var dim = numeric.dim;
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof x === 'object') { if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(x), 0, VV); else x = numeric._biforeach2(x, y, dim(x), 0, VS); }
      else if (typeof y === 'object') x = numeric._biforeach2(x, y, dim(y), 0, SV);
      else x = Math.min(x, y);
    }
    return x;
  };
  numeric['min'] = numeric['min'];
  numeric['mineqV'] = function (ret, x) { var min = Math.min; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = min(ret[i], x[i]); } };
  numeric['mineqS'] = function (ret, x) { var min = Math.min; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = min(ret[i], x); } };
  numeric['mineq'] = function () {
    var n = arguments.length, i, x = arguments[0], y;
    var V = numeric['mineqV'], S = numeric['mineqS'];
    var s = numeric.dim(x);
    for (i = 1; i !== n; ++i) {
      y = arguments[i];
      if (typeof y === 'object') numeric._biforeach(x, y, s, 0, V);
      else numeric._biforeach(x, y, s, 0, S);
    }
    return x;
  };
  numeric['negeqV'] = function (ret) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = -ret[i]; } return ret; };
  numeric['negeq'] = function (x) {
    if (typeof x !== 'object') return -x;
    var V = numeric['negeqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['negV'] = function (x) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = -x[i]; } return ret; };
  numeric['neg'] = function (x) {
    if (typeof x !== 'object') return -x;
    var V = numeric['negV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['noteqV'] = function (ret) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = !ret[i]; } return ret; };
  numeric['noteq'] = function (x) {
    if (typeof x !== 'object') return !x;
    var V = numeric['noteqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['notV'] = function (x) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = !x[i]; } return ret; };
  numeric['not'] = function (x) {
    if (typeof x !== 'object') return !x;
    var V = numeric['notV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['bnoteqV'] = function (ret) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ~ret[i]; } return ret; };
  numeric['bnoteq'] = function (x) {
    if (typeof x !== 'object') return ~x;
    var V = numeric['bnoteqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['bnotV'] = function (x) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = ~x[i]; } return ret; };
  numeric['bnot'] = function (x) {
    if (typeof x !== 'object') return ~x;
    var V = numeric['bnotV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['cloneeqV'] = function (ret) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ret[i]; } return ret; };
  numeric['cloneeq'] = function (x) {
    if (typeof x !== 'object') return x;
    var V = numeric['cloneeqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['cloneV'] = function (x) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = x[i]; } return ret; };
  numeric['clone'] = function (x) {
    if (typeof x !== 'object') return x;
    var V = numeric['cloneV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['abseqV'] = function (ret) { var abs = Math.abs; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = abs(ret[i]); } return ret; };
  numeric['abseq'] = function (x) {
    if (typeof x !== 'object') return abs(x);
    var V = numeric['abseqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['absV'] = function (x) { var abs = Math.abs; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = abs(x[i]); } return ret; };
  numeric['abs'] = function (x) {
    if (typeof x !== 'object') return abs(x);
    var V = numeric['absV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['acoseqV'] = function (ret) { var acos = Math.acos; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = acos(ret[i]); } return ret; };
  numeric['acoseq'] = function (x) {
    if (typeof x !== 'object') return acos(x);
    var V = numeric['acoseqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['acosV'] = function (x) { var acos = Math.acos; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = acos(x[i]); } return ret; };
  numeric['acos'] = function (x) {
    if (typeof x !== 'object') return acos(x);
    var V = numeric['acosV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['asineqV'] = function (ret) { var asin = Math.asin; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = asin(ret[i]); } return ret; };
  numeric['asineq'] = function (x) {
    if (typeof x !== 'object') return asin(x);
    var V = numeric['asineqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['asinV'] = function (x) { var asin = Math.asin; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = asin(x[i]); } return ret; };
  numeric['asin'] = function (x) {
    if (typeof x !== 'object') return asin(x);
    var V = numeric['asinV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['ataneqV'] = function (ret) { var atan = Math.atan; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = atan(ret[i]); } return ret; };
  numeric['ataneq'] = function (x) {
    if (typeof x !== 'object') return atan(x);
    var V = numeric['ataneqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['atanV'] = function (x) { var atan = Math.atan; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = atan(x[i]); } return ret; };
  numeric['atan'] = function (x) {
    if (typeof x !== 'object') return atan(x);
    var V = numeric['atanV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['ceileqV'] = function (ret) { var ceil = Math.ceil; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = ceil(ret[i]); } return ret; };
  numeric['ceileq'] = function (x) {
    if (typeof x !== 'object') return ceil(x);
    var V = numeric['ceileqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['ceilV'] = function (x) { var ceil = Math.ceil; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = ceil(x[i]); } return ret; };
  numeric['ceil'] = function (x) {
    if (typeof x !== 'object') return ceil(x);
    var V = numeric['ceilV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['coseqV'] = function (ret) { var cos = Math.cos; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = cos(ret[i]); } return ret; };
  numeric['coseq'] = function (x) {
    if (typeof x !== 'object') return cos(x);
    var V = numeric['coseqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['cosV'] = function (x) { var cos = Math.cos; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = cos(x[i]); } return ret; };
  numeric['cos'] = function (x) {
    if (typeof x !== 'object') return cos(x);
    var V = numeric['cosV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['expeqV'] = function (ret) { var exp = Math.exp; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = exp(ret[i]); } return ret; };
  numeric['expeq'] = function (x) {
    if (typeof x !== 'object') return exp(x);
    var V = numeric['expeqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['expV'] = function (x) { var exp = Math.exp; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = exp(x[i]); } return ret; };
  numeric['exp'] = function (x) {
    if (typeof x !== 'object') return exp(x);
    var V = numeric['expV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['flooreqV'] = function (ret) { var floor = Math.floor; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = floor(ret[i]); } return ret; };
  numeric['flooreq'] = function (x) {
    if (typeof x !== 'object') return floor(x);
    var V = numeric['flooreqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['floorV'] = function (x) { var floor = Math.floor; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = floor(x[i]); } return ret; };
  numeric['floor'] = function (x) {
    if (typeof x !== 'object') return floor(x);
    var V = numeric['floorV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['logeqV'] = function (ret) { var log = Math.log; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = log(ret[i]); } return ret; };
  numeric['logeq'] = function (x) {
    if (typeof x !== 'object') return log(x);
    var V = numeric['logeqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['logV'] = function (x) { var log = Math.log; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = log(x[i]); } return ret; };
  numeric['log'] = function (x) {
    if (typeof x !== 'object') return log(x);
    var V = numeric['logV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['roundeqV'] = function (ret) { var round = Math.round; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = round(ret[i]); } return ret; };
  numeric['roundeq'] = function (x) {
    if (typeof x !== 'object') return round(x);
    var V = numeric['roundeqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['roundV'] = function (x) { var round = Math.round; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = round(x[i]); } return ret; };
  numeric['round'] = function (x) {
    if (typeof x !== 'object') return round(x);
    var V = numeric['roundV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['sineqV'] = function (ret) { var sin = Math.sin; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = sin(ret[i]); } return ret; };
  numeric['sineq'] = function (x) {
    if (typeof x !== 'object') return sin(x);
    var V = numeric['sineqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['sinV'] = function (x) { var sin = Math.sin; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = sin(x[i]); } return ret; };
  numeric['sin'] = function (x) {
    if (typeof x !== 'object') return sin(x);
    var V = numeric['sinV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['sqrteqV'] = function (ret) { var sqrt = Math.sqrt; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = sqrt(ret[i]); } return ret; };
  numeric['sqrteq'] = function (x) {
    if (typeof x !== 'object') return sqrt(x);
    var V = numeric['sqrteqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['sqrtV'] = function (x) { var sqrt = Math.sqrt; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = sqrt(x[i]); } return ret; };
  numeric['sqrt'] = function (x) {
    if (typeof x !== 'object') return sqrt(x);
    var V = numeric['sqrtV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['taneqV'] = function (ret) { var tan = Math.tan; var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = tan(ret[i]); } return ret; };
  numeric['taneq'] = function (x) {
    if (typeof x !== 'object') return tan(x);
    var V = numeric['taneqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['tanV'] = function (x) { var tan = Math.tan; var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = tan(x[i]); } return ret; };
  numeric['tan'] = function (x) {
    if (typeof x !== 'object') return tan(x);
    var V = numeric['tanV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['isNaNeqV'] = function (ret) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = isNaN(ret[i]); } return ret; };
  numeric['isNaNeq'] = function (x) {
    if (typeof x !== 'object') return isNaN(x);
    var V = numeric['isNaNeqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['isNaNV'] = function (x) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = isNaN(x[i]); } return ret; };
  numeric['isNaN'] = function (x) {
    if (typeof x !== 'object') return isNaN(x);
    var V = numeric['isNaNV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['isFiniteeqV'] = function (ret) { var _n = ret.length, i; for (i = _n - 1; i !== -1; --i) { ret[i] = isFinite(ret[i]); } return ret; };
  numeric['isFiniteeq'] = function (x) {
    if (typeof x !== 'object') return isFinite(x);
    var V = numeric['isFiniteeqV'];
    var s = numeric.dim(x);
    numeric._foreach(x, s, 0, V);
    return x;
  };
  numeric['isFiniteV'] = function (x) { var _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = isFinite(x[i]); } return ret; };
  numeric['isFinite'] = function (x) {
    if (typeof x !== 'object') return isFinite(x);
    var V = numeric['isFiniteV'];
    var s = numeric.dim(x);
    return numeric._foreach2(x, s, 0, V);
  };
  numeric['anyV'] = function (x) {
    var accum = false;
    var _n = x.length, i, xi;
    for (i = _n - 1; i !== -1; --i) { xi = x[i]; if (xi) return true; }
    return accum;
  };
  numeric['any'] = function (x, s, k) {
    var accum = false;
    if (typeof x !== 'object') { var xi = x; if (xi) return true; return accum; }
    if (typeof s === 'undefined') s = numeric.dim(x);
    if (typeof k === 'undefined') k = 0;
    if (k === s.length - 1) return numeric['anyV'](x);
    var xi, n = x.length, i;
    for (i = n - 1; i !== -1; --i) { xi = numeric['any'](x[i]); if (xi) return true; }
    return accum;
  };
  numeric['allV'] = function (x) {
    var accum = true;
    var _n = x.length, i, xi;
    for (i = _n - 1; i !== -1; --i) { xi = x[i]; if (!xi) return false; }
    return accum;
  };
  numeric['all'] = function (x, s, k) {
    var accum = true;
    if (typeof x !== 'object') { var xi = x; if (!xi) return false; return accum; }
    if (typeof s === 'undefined') s = numeric.dim(x);
    if (typeof k === 'undefined') k = 0;
    if (k === s.length - 1) return numeric['allV'](x);
    var xi, n = x.length, i;
    for (i = n - 1; i !== -1; --i) { xi = numeric['all'](x[i]); if (!xi) return false; }
    return accum;
  };
  numeric['sumV'] = function (x) {
    var accum = 0;
    var _n = x.length, i, xi;
    for (i = _n - 1; i !== -1; --i) { xi = x[i]; accum += xi; }
    return accum;
  };
  numeric['sum'] = function (x, s, k) {
    var accum = 0;
    if (typeof x !== 'object') { var xi = x; accum += xi; return accum; }
    if (typeof s === 'undefined') s = numeric.dim(x);
    if (typeof k === 'undefined') k = 0;
    if (k === s.length - 1) return numeric['sumV'](x);
    var xi, n = x.length, i;
    for (i = n - 1; i !== -1; --i) { xi = numeric['sum'](x[i]); accum += xi; }
    return accum;
  };
  numeric['prodV'] = function (x) {
    var accum = 1;
    var _n = x.length, i, xi;
    for (i = _n - 1; i !== -1; --i) { xi = x[i]; accum *= xi; }
    return accum;
  };
  numeric['prod'] = function (x, s, k) {
    var accum = 1;
    if (typeof x !== 'object') { var xi = x; accum *= xi; return accum; }
    if (typeof s === 'undefined') s = numeric.dim(x);
    if (typeof k === 'undefined') k = 0;
    if (k === s.length - 1) return numeric['prodV'](x);
    var xi, n = x.length, i;
    for (i = n - 1; i !== -1; --i) { xi = numeric['prod'](x[i]); accum *= xi; }
    return accum;
  };
  numeric['norm2SquaredV'] = function (x) {
    var accum = 0;
    var _n = x.length, i, xi;
    for (i = _n - 1; i !== -1; --i) { xi = x[i]; accum += xi * xi; }
    return accum;
  };
  numeric['norm2Squared'] = function (x, s, k) {
    var accum = 0;
    if (typeof x !== 'object') { var xi = x; accum += xi * xi; return accum; }
    if (typeof s === 'undefined') s = numeric.dim(x);
    if (typeof k === 'undefined') k = 0;
    if (k === s.length - 1) return numeric['norm2SquaredV'](x);
    var xi, n = x.length, i;
    for (i = n - 1; i !== -1; --i) { xi = numeric['norm2Squared'](x[i]); accum += xi * xi; }
    return accum;
  };
  numeric['norminfV'] = function (x) {
    var accum = 0, max = Math.max, abs = Math.abs;
    var _n = x.length, i, xi;
    for (i = _n - 1; i !== -1; --i) { xi = x[i]; accum = max(accum, abs(xi)); }
    return accum;
  };
  numeric['norminf'] = function (x, s, k) {
    var accum = 0, max = Math.max, abs = Math.abs;
    if (typeof x !== 'object') { var xi = x; accum = max(accum, abs(xi)); return accum; }
    if (typeof s === 'undefined') s = numeric.dim(x);
    if (typeof k === 'undefined') k = 0;
    if (k === s.length - 1) return numeric['norminfV'](x);
    var xi, n = x.length, i;
    for (i = n - 1; i !== -1; --i) { xi = numeric['norminf'](x[i]); accum = max(accum, abs(xi)); }
    return accum;
  };
  numeric['norm1V'] = function (x) {
    var accum = 0, abs = Math.abs;
    var _n = x.length, i, xi;
    for (i = _n - 1; i !== -1; --i) { xi = x[i]; accum += abs(xi) }
    return accum;
  };
  numeric['norm1'] = function (x, s, k) {
    var accum = 0, abs = Math.abs;
    if (typeof x !== 'object') { var xi = x; accum += abs(xi) return accum; }
    if (typeof s === 'undefined') s = numeric.dim(x);
    if (typeof k === 'undefined') k = 0;
    if (k === s.length - 1) return numeric['norm1V'](x);
    var xi, n = x.length, i;
    for (i = n - 1; i !== -1; --i) { xi = numeric['norm1'](x[i]); accum += abs(xi) }
    return accum;
  };
  numeric['supV'] = function (x) {
    var accum = -Infinity, max = Math.max;
    var _n = x.length, i, xi;
    for (i = _n - 1; i !== -1; --i) { xi = x[i]; accum = max(accum, xi); }
    return accum;
  };
  numeric['sup'] = function (x, s, k) {
    var accum = -Infinity, max = Math.max;
    if (typeof x !== 'object') { var xi = x; accum = max(accum, xi); return accum; }
    if (typeof s === 'undefined') s = numeric.dim(x);
    if (typeof k === 'undefined') k = 0;
    if (k === s.length - 1) return numeric['supV'](x);
    var xi, n = x.length, i;
    for (i = n - 1; i !== -1; --i) { xi = numeric['sup'](x[i]); accum = max(accum, xi); }
    return accum;
  };
  numeric['infV'] = function (x) {
    var accum = Infinity, min = Math.min;
    var _n = x.length, i, xi;
    for (i = _n - 1; i !== -1; --i) { xi = x[i]; accum = min(accum, xi); }
    return accum;
  };
  numeric['inf'] = function (x, s, k) {
    var accum = Infinity, min = Math.min;
    if (typeof x !== 'object') { var xi = x; accum = min(accum, xi); return accum; }
    if (typeof s === 'undefined') s = numeric.dim(x);
    if (typeof k === 'undefined') k = 0;
    if (k === s.length - 1) return numeric['infV'](x);
    var xi, n = x.length, i;
    for (i = n - 1; i !== -1; --i) { xi = numeric['inf'](x[i]); accum = min(accum, xi); }
    return accum;
  };
  numeric['truncVV'] = function (x, y) { var round = Math.round, _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = round(x[i] / y[i]) * y[i]; } return ret; };
  numeric['truncVS'] = function (x, y) { var round = Math.round, _n = x.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = round(x[i] / y) * y; } return ret; };
  numeric['truncSV'] = function (x, y) { var round = Math.round, _n = y.length, i, ret = Array(_n); for (i = _n - 1; i !== -1; --i) { ret[i] = round(x / y[i]) * y[i]; } return ret; };
})();