#!/usr/bin/env node
// Runs numeric.js code-generation in Node.js (where new Function is allowed),
// then serializes every generated function as static source so webgazer.js
// can be patched to remove all eval/new-Function calls (banned in MV3).

const ops2 = {
  add: '+', sub: '-', mul: '*', div: '/', mod: '%',
  and: '&&', or: '||',
  eq: '===', neq: '!==', lt: '<', gt: '>', leq: '<=', geq: '>=',
  band: '&', bor: '|', bxor: '^', lshift: '<<', rshift: '>>', rrshift: '>>>'
};
const mathfuns2 = ['atan2', 'pow', 'max', 'min'];
const opseq = {
  addeq: '+=', subeq: '-=', muleq: '*=', diveq: '/=', modeq: '%=',
  lshifteq: '<<=', rshifteq: '>>=', rrshifteq: '>>>=',
  bandeq: '&=', boreq: '|=', bxoreq: '^='
};
const mathfuns = ['abs', 'acos', 'asin', 'atan', 'ceil', 'cos',
  'exp', 'floor', 'log', 'round', 'sin', 'sqrt', 'tan',
  'isNaN', 'isFinite'];
const ops1 = { neg: '-', not: '!', bnot: '~', clone: '' };
const mapreducers = {
  any: ['if(xi) return true;', 'var accum = false;'],
  all: ['if(!xi) return false;', 'var accum = true;'],
  sum: ['accum += xi;', 'var accum = 0;'],
  prod: ['accum *= xi;', 'var accum = 1;'],
  norm2Squared: ['accum += xi*xi;', 'var accum = 0;'],
  norminf: ['accum = max(accum,abs(xi));', 'var accum = 0, max = Math.max, abs = Math.abs;'],
  norm1: ['accum += abs(xi);', 'var accum = 0, abs = Math.abs;'],
  sup: ['accum = max(accum,xi);', 'var accum = -Infinity, max = Math.max;'],
  inf: ['accum = min(accum,xi);', 'var accum = Infinity, min = Math.min;']
};

// Add mathfuns2 into ops2
for (const o of mathfuns2) ops2[o] = o;

const lines = [];
lines.push('// AUTO-GENERATED by pregen_numeric.js — do not edit by hand');
lines.push('// Replaces all new Function() calls in numeric.js for MV3 CSP compliance');
lines.push('(function(){');

// ── ops2 ──────────────────────────────────────────────────────────────────────
for (const [i, o] of Object.entries(ops2)) {
  const isMath = mathfuns2.includes(i);
  const setupLine = isMath ? `var ${o} = Math.${o};` : '';

  // VV: ret[i] = x[i] op y[i]
  const bodyVV = isMath ? `ret[i] = ${o}(x[i],y[i]);` : `ret[i] = x[i] ${o} y[i];`;
  lines.push(`numeric['${i}VV'] = function(x,y){${setupLine} var _n=x.length,i,ret=Array(_n); for(i=_n-1;i!==-1;--i){${bodyVV}} return ret;};`);

  // SV: ret[i] = x op y[i]
  const bodySV = isMath ? `ret[i] = ${o}(x,y[i]);` : `ret[i] = x ${o} y[i];`;
  lines.push(`numeric['${i}SV'] = function(x,y){${setupLine} var _n=y.length,i,ret=Array(_n); for(i=_n-1;i!==-1;--i){${bodySV}} return ret;};`);

  // VS: ret[i] = x[i] op y
  const bodyVS = isMath ? `ret[i] = ${o}(x[i],y);` : `ret[i] = x[i] ${o} y;`;
  lines.push(`numeric['${i}VS'] = function(x,y){${setupLine} var _n=x.length,i,ret=Array(_n); for(i=_n-1;i!==-1;--i){${bodyVS}} return ret;};`);

  // op itself: dispatch VV/VS/SV/scalar
  const codeeqScalar = isMath
    ? `x = Math.${o}(x,y)`
    : (opseq[i + 'eq'] ? `x ${o}= y` : `x = x ${o} y`);
  lines.push(`numeric['${i}'] = function(){
  var n=arguments.length,i,x=arguments[0],y;
  var VV=numeric['${i}VV'],VS=numeric['${i}VS'],SV=numeric['${i}SV'];
  var dim=numeric.dim;
  for(i=1;i!==n;++i){
    y=arguments[i];
    if(typeof x==='object'){if(typeof y==='object') x=numeric._biforeach2(x,y,dim(x),0,VV); else x=numeric._biforeach2(x,y,dim(x),0,VS);}
    else if(typeof y==='object') x=numeric._biforeach2(x,y,dim(y),0,SV);
    else ${codeeqScalar};
  }
  return x;
};`);
  if (isMath) {
    lines.push(`numeric['${o}'] = numeric['${i}'];`);
  }

  // eqV: ret[i] op= x[i]
  const bodyEqV = isMath ? `ret[i] = ${o}(ret[i],x[i]);` : (opseq[i + 'eq'] ? `ret[i] ${o}= x[i];` : `ret[i] = ret[i] ${o} x[i];`);
  lines.push(`numeric['${i}eqV'] = function(ret,x){${setupLine} var _n=ret.length,i; for(i=_n-1;i!==-1;--i){${bodyEqV}}};`);

  // eqS: ret[i] op= x
  const bodyEqS = isMath ? `ret[i] = ${o}(ret[i],x);` : (opseq[i + 'eq'] ? `ret[i] ${o}= x;` : `ret[i] = ret[i] ${o} x;`);
  lines.push(`numeric['${i}eqS'] = function(ret,x){${setupLine} var _n=ret.length,i; for(i=_n-1;i!==-1;--i){${bodyEqS}}};`);

  // eq: dispatch and mutate
  lines.push(`numeric['${i}eq'] = function(){
  var n=arguments.length,i,x=arguments[0],y;
  var V=numeric['${i}eqV'],S=numeric['${i}eqS'];
  var s=numeric.dim(x);
  for(i=1;i!==n;++i){
    y=arguments[i];
    if(typeof y==='object') numeric._biforeach(x,y,s,0,V);
    else numeric._biforeach(x,y,s,0,S);
  }
  return x;
};`);
}

// ── ops1 + mathfuns ───────────────────────────────────────────────────────────
const allOps1 = Object.assign({}, ops1);
for (const f of mathfuns) allOps1[f] = f;

for (const [i, o] of Object.entries(allOps1)) {
  const isMathFun = mathfuns.includes(i);
  const setupLine = (isMathFun && (o in Math)) ? `var ${o} = Math.${o};` : '';
  const applyFn = isMathFun ? `${o}(ret[i])` : `${o}ret[i]`;
  const applyFnV = isMathFun ? `${o}(x[i])` : `${o}x[i]`;
  const applyScalar = isMathFun ? `${o}(x)` : `${o}x`;

  // eqV: ret[i] = op(ret[i])
  lines.push(`numeric['${i}eqV'] = function(ret){${setupLine} var _n=ret.length,i; for(i=_n-1;i!==-1;--i){ret[i]=${applyFn};} return ret;};`);

  // eq: dispatch
  lines.push(`numeric['${i}eq'] = function(x){
  if(typeof x!=='object') return ${applyScalar};
  var V=numeric['${i}eqV'];
  var s=numeric.dim(x);
  numeric._foreach(x,s,0,V);
  return x;
};`);

  // V: create new array
  lines.push(`numeric['${i}V'] = function(x){${setupLine} var _n=x.length,i,ret=Array(_n); for(i=_n-1;i!==-1;--i){ret[i]=${applyFnV};} return ret;};`);

  // op itself: dispatch
  lines.push(`numeric['${i}'] = function(x){
  if(typeof x!=='object') return ${applyScalar};
  var V=numeric['${i}V'];
  var s=numeric.dim(x);
  return numeric._foreach2(x,s,0,V);
};`);
}

// ── mapreducers ───────────────────────────────────────────────────────────────
for (const [i, [body, init]] of Object.entries(mapreducers)) {
  // V version (1-D, uses mapreduce2 pattern)
  lines.push(`numeric['${i}V'] = function(x){
  ${init}
  var _n=x.length,i,xi;
  for(i=_n-1;i!==-1;--i){ xi=x[i]; ${body} }
  return accum;
};`);

  // recursive version
  lines.push(`numeric['${i}'] = function(x,s,k){
  ${init}
  if(typeof x!=='object'){ var xi=x; ${body} return accum; }
  if(typeof s==='undefined') s=numeric.dim(x);
  if(typeof k==='undefined') k=0;
  if(k===s.length-1) return numeric['${i}V'](x);
  var xi, n=x.length,i;
  for(i=n-1;i!==-1;--i){ xi=numeric['${i}'](x[i]); ${body} }
  return accum;
};`);
}

// ── trunc functions (were using numeric.pointwise) ────────────────────────────
lines.push(`numeric['truncVV'] = function(x,y){ var round=Math.round,_n=x.length,i,ret=Array(_n); for(i=_n-1;i!==-1;--i){ret[i]=round(x[i]/y[i])*y[i];} return ret; };`);
lines.push(`numeric['truncVS'] = function(x,y){ var round=Math.round,_n=x.length,i,ret=Array(_n); for(i=_n-1;i!==-1;--i){ret[i]=round(x[i]/y)*y;} return ret; };`);
lines.push(`numeric['truncSV'] = function(x,y){ var round=Math.round,_n=y.length,i,ret=Array(_n); for(i=_n-1;i!==-1;--i){ret[i]=round(x/y[i])*y[i];} return ret; };`);

lines.push('})();');

const fs = require('fs');
fs.writeFileSync('numeric_pregenerated.js', lines.join('\n'));
console.log('Written numeric_pregenerated.js (' + lines.length + ' lines)');
